pretrained_text_encoder_path: models/FLUX/FLUX.1-dev/text_encoder/model.safetensors
pretrained_text_encoder_2_path: models/FLUX/FLUX.1-dev/text_encoder_2
pretrained_dit_path: models/FLUX/FLUX.1-dev/flux1-dev.safetensors
pretrained_vae_path: models/FLUX/FLUX.1-dev/ae.safetensors
dataset_path: 'path_to_your_dataset.jsonl'
output_path: workdirs/decoder/train
height: 1024
width: 1024
dataloader_num_workers: 12
learning_rate: 0.0001
use_gradient_checkpointing: True
accumulate_grad_batches: 16
batch_size: 1
training_strategy: 'deepspeed_stage_3'
precision: 'bf16'
steps_per_epoch: 64000
max_epochs: 10
lr_warmup_steps: 500
